### ISSUE TITLE
Vulkan Todo List

### ISSUE THREAD

**Issue by droc101** [droc101/c-game-engine#10]
## General
- [ ] Only wait for fences when needed
- [ ] Documentation. A lot of it.
- [ ] Check maxPerStageDescriptorSampledImages
- [ ] Race condition can cause out of date pipeline
- [ ] Resizing buffer causes single(?) frame flicker
- [ ] Any form of zero can be omitted from structs initialized with designated initialization as outlined [here](https://gcc.gnu.org/onlinedocs/gcc/Designated-Inits.html)
- [ ] Fix #26 
- [ ] Replace `VulkanTest` with a function
- [ ] Cleanup `VulkanHelpers.h` (macros, structs, and global vars)
- [x] actor y positions
  - 0.0 is the default (aligned with level walls)
- [x] camera y position (though this will likely have to exist to mimic `GlobalState.FakeHeight`)
- [x] floor with texture (didn't do this in 2d because i'd like it to be projected properly)
  - could be like a 100x100 quad or something under the player with uvs that shift with player position and rotation
- [x] configurable fake shadows (kinda like in leafy's adventure) for actors
  - size
  - opacity should vary based on distance from bottom of actor wall to ground, but never get fully opaque or transparent
- [x] actor wall heights
  - "normal" height should be 1.0
  - should should extend height/2 units from actor y position
  - texture should always fill full height of wall
- [x] Transparency!
- [x] Replace `List` macro for better code readability
- [x] Clang-tidy
- [x] Split into multiple files
- [x] Show error if Vulkan fails to init and prompt to exit or restart using OpenGL
- [x] Further testing of `VK_Cleanup` with partially initialized Vulkan
- [x] Mips/MSAA options
- [x] Clear color image
- [x] Fix weird texture bugs
  - [x] Text when maximized (Windows + Linux)
  - [x] "Corruption" (AMD Drivers)
  - [x] Wiggly logo (NVIDIA drivers)
    - Tested to be caused by tessellation shaders. (NVIDIA driver bug???)
- [x] [ghost bug thing](https://discord.com/channels/@me/887131461965205524/1313233788783824937) (linux intel igpu `xe,i915` driver)
## Rendering Abstractions
- [x] Drawing.c SetTexParams
- [x] Drawing.c DrawLine
- [x] Drawing.c DrawOutlineRect
- [x] Drawing.c DrawTexture
- [x] Drawing.c DrawTextureMod
- [x] Drawing.c DrawTextureRegion
- [x] Drawing.c DrawTextureRegionMod
- [x] Drawing.c ClearColor
- [x] Drawing.c ClearScreen
- [x] Drawing.c ClearDepthOnly
- [x] Drawing.c DrawRect
- [x] RenderingHelpers.c RenderPreInit
- [x] RenderingHelpers.c RenderInit
- [x] RenderingHelpers.c RenderDestroy
- [x] RenderingHelpers.c FrameStart
- [x] RenderingHelpers.c FrameEnd
- [x] RenderingHelpers.c RenderLevel3D
- [x] RenderingHelpers.c UpdateViewportSize
- [x] RenderingHelpers.c WindowObscured
- [x] RenderingHelpers.c WindowRestored
- [x] RenderingHelpers.c DrawBatchedQuadsTextured
- [x] RenderingHelpers.c DrawBatchedQuadsColored
- [x] RenderingHelpers.c X_TO_NDC
- [x] RenderingHelpers.c Y_TO_NDC
# Potential Optimizations
- [ ] Instanced shadows
- [ ] [Listen to the smart people](https://developer.nvidia.com/blog/tag/advanced-api-performance)
- [ ] Separate color attachment for parts of UI that do not change
- [ ] Use UiStackPush to get constant values to local memory?
- [ ] Reuse memory allocations
- [ ] Anything not being updated often should be on device local memory
- [ ] Don't update descriptor sets unless needed
- [ ] Queue families
- [ ] Pack & pad sharder inputs and outputs
- [ ] Use VkSwapchainCreateInfoKHR::oldSwapchain for swapchain recreation
- [ ] Threads! (I hate this but it is how performance is made)
- [x] Heap vs stack allocation
- [x] Linked lists are slow. Fix it.
- [x] Blocked memory allocation
# TODO Before Merge
- [x] Compile and run on windows
- [x] Memory safety (for example check mallocs)
- [x] Update docs to list packages/libs needed for vulkan
- [x] Texture issues with AMD
- [x] print gpu and vulkan version/driver version info on startup
- [x] Push constants (Careful of limits!!)
- [x] Use VkPhysicalDeviceLimits to check values
- [x] Benchmark level walls become triangles after a certain point because why not
- [x] Failed init testing
- [x] Only draw walls if renderlevel3d was called

**Comment by droc101** [comment]
@NBT22 Update this with current state after Luna and/or split into new issues and close this?
