### ISSUE TITLE
physics branch wishlist

### ISSUE THREAD

**Issue by droc101** [droc101/c-game-engine#18]
- [x] fix #9
- [x] port #12 
- [x] allow any speed/velocity
- [x] actors can have various hitbox types, as well as test against an arbirarry hitbox when they want to:
  - [x] rectangle collision (can rotate around y axis)
  - [x] circle collision (no need to rotate)
  - [x] polygon collision (with rotation)
  - [x] wall hitbox (can be based on a box)
- [x] actor pathfinding system
  - maybe add a variance option so it can optionally not just take the fastest path because that might be strange
  - should account for the level walls as well as any solid actor walls (like a door or something)
  - optional max distance
  - optional line-of-sight
    - not sure if this would be part of the pf system but maybe stop following if los is broken for n ticks
 - [x] document like all the stuff you added or changed
